import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Organic Honeycrisp Apples',
    price: 3.99,
    unit: '1 lb bag',
    category: 'Fruits & Vegetables',
    description: 'Crisp, sweet, and slightly tart organic honeycrisp apples. Perfect for snacking, baking, or salads.',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=400&q=80',
    inventory: 45,
  },
  {
    id: 'prod-2',
    name: 'Organic Bananas Bunch',
    price: 1.89,
    unit: 'approx. 5-6 bananas',
    category: 'Fruits & Vegetables',
    description: 'Fresh organic sweet bananas, loaded with potassium and natural energy. Great for smoothies or on-the-go snacking.',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80',
    inventory: 60,
  },
  {
    id: 'prod-3',
    name: 'Baby Spinach Organic',
    price: 3.49,
    unit: '5 oz container',
    category: 'Fruits & Vegetables',
    description: 'Pre-washed, tender organic baby spinach leaves, packed with iron and vitamins. Ready to enjoy in fresh salads or sauted dishes.',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=400&q=80',
    inventory: 30,
  },
  {
    id: 'prod-4',
    name: 'Fresh Hass Avocados',
    price: 4.99,
    unit: '4 pack',
    category: 'Fruits & Vegetables',
    description: 'Creamy Hass avocados, perfect for freshly made guacamole, slicing onto toast, or adding rich flavor to healthy salads.',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=400&q=80',
    inventory: 25,
  },
  {
    id: 'prod-5',
    name: 'Organic Whole Milk 3.25%',
    price: 4.49,
    unit: '0.5 gallon',
    category: 'Dairy & Eggs',
    description: 'Rich and creamy pasteurized organic whole milk from pasture-raised cows. Excellent source of calcium and vitamin D.',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
    inventory: 40,
  },
  {
    id: 'prod-6',
    name: 'Grade A Free-Range Brown Eggs',
    price: 5.29,
    unit: '12 count',
    category: 'Dairy & Eggs',
    description: 'Farm-fresh, large, free-range brown eggs laid by hens with access to outdoor pastures. Perfect for breakfast or baking.',
    image: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=400&q=80',
    inventory: 35,
  },
  {
    id: 'prod-7',
    name: 'Artisanal Sourdough Boule',
    price: 5.99,
    unit: '24 oz loaf',
    category: 'Bakery & Bread',
    description: 'Locally baked crusty sourdough bread with a soft, airy interior and classic tangy flavor. Great for grilled cheese or dipping in soup.',
    image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=400&q=80',
    inventory: 15,
  },
  {
    id: 'prod-8',
    name: 'All-Butter Croissants',
    price: 4.49,
    unit: '4 pack',
    category: 'Bakery & Bread',
    description: 'Flaky, golden-brown croissants layered with pure cream butter. Heat them up for a warm, melt-in-your-mouth morning treat.',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=400&q=80',
    inventory: 18,
  },
  {
    id: 'prod-9',
    name: 'Fresh Atlantic Salmon Fillet',
    price: 14.99,
    unit: '1 lb',
    category: 'Meat & Seafood',
    description: 'Rich, high-quality Atlantic salmon fillets. Naturally packed with omega-3 fatty acids. Ideal for baking, pan-searing, or grilling.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=400&q=80',
    inventory: 12,
  },
  {
    id: 'prod-10',
    name: 'Organic Boneless Chicken Breasts',
    price: 8.99,
    unit: '1.25 lbs',
    category: 'Meat & Seafood',
    description: 'Plump, skinless, boneless organic chicken breasts raised with 100% organic vegetarian feed and no added antibiotics.',
    image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=400&q=80',
    inventory: 20,
  },
  {
    id: 'prod-11',
    name: 'Extra Virgin Cold Pressed Olive Oil',
    price: 11.99,
    unit: '16.9 fl oz',
    category: 'Pantry & Snacks',
    description: 'First cold-pressed extra virgin olive oil imported from Spanish groves. Rich, fruity profile with a subtle peppery finish.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80',
    inventory: 22,
  },
  {
    id: 'prod-12',
    name: 'Organic Raw Wildflower Honey',
    price: 6.79,
    unit: '12 oz jar',
    category: 'Pantry & Snacks',
    description: 'Unfiltered, pure wildflower honey sourced from sustainable US apiaries. Perfect natural sweetener for tea, oatmeal, or baking.',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=400&q=80',
    inventory: 25,
  },
  {
    id: 'prod-13',
    name: 'Organic French Roast Ground Coffee',
    price: 9.99,
    unit: '12 oz bag',
    category: 'Beverages',
    description: 'Dark, robust, and smoky organic french roast ground coffee. Crafted from 100% Arabica beans sourced from South America.',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80',
    inventory: 28,
  },
  {
    id: 'prod-14',
    name: 'Sparkling Mineral Water',
    price: 5.49,
    unit: '8 pack / 12 fl oz cans',
    category: 'Beverages',
    description: 'Refreshing sparkling mineral water with a hint of natural lime essence and zero sweeteners. Perfectly bubbly.',
    image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=400&q=80',
    inventory: 30,
  },
  {
    id: 'prod-15',
    name: 'Handcrafted Sea Salt Potato Chips',
    price: 3.29,
    unit: '8 oz bag',
    category: 'Pantry & Snacks',
    description: 'Thick-cut kettle potato chips cooked in small batches and seasoned with pure crystalline sea salt. Exceptional crunch.',
    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=400&q=80',
    inventory: 40,
  },
  {
    id: 'prod-16',
    name: '72% Dark Chocolate with Sea Salt',
    price: 2.99,
    unit: '3.17 oz bar',
    category: 'Pantry & Snacks',
    description: 'Rich Belgian dark chocolate containing 72% cocoa, blended with delicate flakes of French fleur de sel sea salt.',
    image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&w=400&q=80',
    inventory: 50,
  },
];
